use book_store;
CREATE TABLE Book (ID int(10) NOT NULL AUTO_INCREMENT, Title varchar(255), Author varchar(255), Price float, Stock int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Cart (ID int(10) NOT NULL AUTO_INCREMENT, Created_at date, CustomerID int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE CartItem (ID int(10) NOT NULL AUTO_INCREMENT, Quantity int(10), CartID int(10) NOT NULL, BookID int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Customer (ID int(10) NOT NULL AUTO_INCREMENT, Name varchar(255), Email varchar(255), Password varchar(255), PRIMARY KEY (ID));
ALTER TABLE CartItem ADD CONSTRAINT FKCartItem387983 FOREIGN KEY (BookID) REFERENCES Book (ID);
ALTER TABLE CartItem ADD CONSTRAINT FKCartItem202317 FOREIGN KEY (CartID) REFERENCES Cart (ID);
ALTER TABLE Cart ADD CONSTRAINT FKCart195823 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
